### ISSUE TITLE
[Error]: TypeError: Cannot read properties of undefined (reading 'video') 

### ISSUE THREAD

**Issue by rioogp** [wahdalo/tiktok-src#12]
Terdapat error kode
TypeError: Cannot read properties of undefined (reading 'video') at downloadAndUpload (file:///C:/Users/users/Downloads/tiktok-src/index.js:13:33)

![Screenshot_05](https://github.com/wahdalo/tiktok-src/assets/77945629/e9f4bc6d-e659-44a3-89c9-78bc1575a175)

**Comment by fhatur12** [comment]
update

**Comment by wahdalo** [comment]
clone ulang, udah di update
