### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by 3xtazzy** [wahdalo/tiktok-src#15]
Terjadi saat setelah download video lalu popup browser

```
[14:10:59] INFO: Session ditemukan, mencoba akses Facebook...
[14:11:02] Berhasil membuka fb
[14:11:02] TypeError: Cannot read properties of undefined (reading 'click')
[14:11:05] Berhasil membuka fb
[14:11:05] TypeError: Cannot read properties of undefined (reading 'click')
file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51
            this.#timeoutError = new TimeoutError(opts.message);
                                 ^

TimeoutError: Waiting for `FileChooser` failed: 30000ms exceeded
    at new Deferred (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51:34)
    at Deferred.create (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:13:16)
    at CdpPage.waitForFileChooser (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:353:35)
    at file:///C:/Users/eXtazzy/Documents/tiktok-src/lib/browserHandler.js:74:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by tdee912** [comment]
> Terjadi saat setelah download video lalu popup browser
> 
> ```
> [14:10:59] INFO: Session ditemukan, mencoba akses Facebook...
> [14:11:02] Berhasil membuka fb
> [14:11:02] TypeError: Cannot read properties of undefined (reading 'click')
> [14:11:05] Berhasil membuka fb
> [14:11:05] TypeError: Cannot read properties of undefined (reading 'click')
> file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51
>             this.#timeoutError = new TimeoutError(opts.message);
>                                  ^
> 
> TimeoutError: Waiting for `FileChooser` failed: 30000ms exceeded
>     at new Deferred (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51:34)
>     at Deferred.create (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:13:16)
>     at CdpPage.waitForFileChooser (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:353:35)
>     at file:///C:/Users/eXtazzy/Documents/tiktok-src/lib/browserHandler.js:74:14
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

copy paste ulang lagi bang cookie nya, kemungkinan session berakhir

**Comment by 3xtazzy** [comment]
> > Terjadi saat setelah download video lalu popup browser
> > ```
> > [14:10:59] INFO: Session ditemukan, mencoba akses Facebook...
> > [14:11:02] Berhasil membuka fb
> > [14:11:02] TypeError: Cannot read properties of undefined (reading 'click')
> > [14:11:05] Berhasil membuka fb
> > [14:11:05] TypeError: Cannot read properties of undefined (reading 'click')
> > file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51
> >             this.#timeoutError = new TimeoutError(opts.message);
> >                                  ^
> > 
> > TimeoutError: Waiting for `FileChooser` failed: 30000ms exceeded
> >     at new Deferred (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:51:34)
> >     at Deferred.create (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:13:16)
> >     at CdpPage.waitForFileChooser (file:///C:/Users/eXtazzy/Documents/tiktok-src/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:353:35)
> >     at file:///C:/Users/eXtazzy/Documents/tiktok-src/lib/browserHandler.js:74:14
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > ```
> 
> copy paste ulang lagi bang cookie nya, kemungkinan session berakhir

Engga bisa bang, errornya itu karena facebook.com/reels/create itu udah gak bisa diakses lagi

**Comment by 3xtazzy** [comment]
Kalo pake page/halaman, kaya gini, tapi kalo pake profile fb biasa, bisa.
![image](https://github.com/wahdalo/tiktok-src/assets/18087260/58d105cd-b1df-4a82-90f4-475c154a3cd7)

**Comment by tdee912** [comment]
> Kalo pake page/halaman, kaya gini, tapi kalo pake profile fb biasa, bisa. Kena block FB ya? ![image](https://private-user-images.githubusercontent.com/18087260/320247723-58d105cd-b1df-4a82-90f4-475c154a3cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTAwNjYsIm5iZiI6MTcxMjQ4OTc2NiwicGF0aCI6Ii8xODA4NzI2MC8zMjAyNDc3MjMtNThkMTA1Y2QtYjFkZi00YTgyLTkwZjQtNDc1YzE1NGEzY2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMzYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzQyOTljMDM5NDA4ODcwNWFiNWIxNTNjY2YzY2JhNzlmZGE1YjdkYWI0NmIwZDcwMDgwOGFiMDkzZWQ4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92yHs_XTPDPAAB1mVaeswWBdEhQTdUZXWE_I45GFfaw)

puppeteer versi berapa itu bang? coba downgrade puppeteernya

**Comment by 3xtazzy** [comment]
Solved, pake puppeteer sesuai versi di version locknya
