### ISSUE TITLE
Unnecessary use of "moment"

### ISSUE THREAD

**Issue by orhanayd** [wahdalo/tiktok-src#31]
We can change moment with "kk-date" its more fast than moment.
new kk_date().format('HH:mm:ss');

**Comment by wahdalo** [comment]
How do I use that?

**Comment by orhanayd** [comment]
browserHandler.js
Line 54;
const date = moment().format('HH:mm:ss')
change to;
const date = new kk_date().format('HH:mm:ss');

**Comment by wahdalo** [comment]
![Uploading image.png…]()
I've tried it and it's an error, does it support import module?

**Comment by wahdalo** [comment]
![Uploading Screenshot 2024-09-23 193243.png…]()

**Comment by orhanayd** [comment]
Image cant load ?

**Comment by orhanayd** [comment]
import module is support. just dont forget when you call put "new";
const date = new kk_date().format('HH:mm:ss');
